<a href="https://colab.research.google.com/github/aditya-03-githere/movie-recommender-system/blob/main/02_recommender_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('processed_movies (2).csv')

In [7]:
df.head()

,title,genres,overview,tagline,popularity,vote_average,details
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,7.7,led woody andy toy live happily room andy birt...
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.712900,6.5,family wedding reignites ancient feud next doo...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7,george bank recovered daughter wedding receive...

In [8]:
df['details'] = df['details'].fillna(' ')
df['genres'] = df['genres'].fillna(' ')

# **Text Vectorization**

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2))

In [11]:
tfidf_matrix = tfidf.fit_transform(df['details'])

# **Calculating Cosine Similarity**

After converting movie descriptions into TF-IDF vectors, cosine similarity
is used to measure the similarity between movies.

The cosine similarity score ranges from -1 to 1. Since TF-IDF vectors contain
non-negative values, movie similarity scores will generally range from 0 to 1.

A higher score indicates that two movies have more similar textual features.

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
def get_recommendations(title,n=10):
  if title not in df['title'].values:
    return ['Movie not found']

  idx = df.index[df['title'].values==title][0]

  sim_scores = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  top_indices = sim_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[top_indices]

In [20]:
get_recommendations('Toy Story', 5)

2996                Toy Story 2
15340               Toy Story 3
24500                 Small Fry
10297    The 40 Year Old Virgin
29174                Hot Splash
Name: title, dtype: object

In [21]:
get_recommendations('Jumanji', 5)

35556             Aschenputtel
21616             Table No. 21
9499                 Word Wars
37408       The Ouija Exorcism
19778    Indie Game: The Movie
Name: title, dtype: object

In [22]:
get_recommendations('Avatar', 5)

26534                  Avatar 2
13880      The Inhabited Island
43405    Moontrap: Target Earth
2457                 The Matrix
26540            Thor: Ragnarok
Name: title, dtype: object

In [26]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))